### ISSUE TITLE
Errata - Several references to .js files instead of .ts files in the book

### ISSUE THREAD

**Issue by softwareliberationarmy** [Apress/Test-Driven-Development-with-React-second-edition-by-Juntao-Qiu#1]
I hope you don't mind me submitting errata from the book here. I could not find another channel to submit feedback. 

There are several places where the book references .js files instead of .ts files. While I haven't read the first edition of this book (the JS one), I imagine these are just files from the first book that were never renamed for the second book. This was not too confusing for me but could be confusing for a beginning developer.

**Comment by abruzzi** [comment]
I think this is a great idea. We can use that as a place for all these discussions. Thanks for bringing it up.

**Comment by abruzzi** [comment]
I'll close this for now, but thanks for posting here I really appreciate it.
