### ISSUE TITLE
Errata - Cypress setup requires additional steps for typescript

### ISSUE THREAD

**Issue by softwareliberationarmy** [Apress/Test-Driven-Development-with-React-second-edition-by-Juntao-Qiu#2]
I hope you don't mind me submitting errata from the book here. I could not find another channel to submit feedback. 

The Cypress setup steps in the book do not include any TypeScript configuration, possibly something that wasn't needed in version 1 of the textbook but was overlooked for the TypeScript version. When I started running the cypress tests, I was seeing errors with the methods off the cy and expect objects. Adding the tsconfig.json file to the cypress directory as indicated [here](https://docs.cypress.io/guides/tooling/typescript-support?utm_source=pocket_saves) fixed the issue. 

You might want to call this out explicitly in the setup.

**Comment by abruzzi** [comment]
Awesome, thank you so much @softwareliberationarmy
