### ISSUE TITLE
Errata - do TS files returning JSX need to be TSX files? 

### ISSUE THREAD

**Issue by softwareliberationarmy** [Apress/Test-Driven-Development-with-React-second-edition-by-Juntao-Qiu#3]
I hope you don't mind me submitting errata from the book here. I could not find another channel to submit feedback. 

In Chapter 6 when you implement the booklist and then refactor the logic out to several separate files (great section, by the way), I was seeing errors in the TS files that returned JSX (BookList.ts, for example). I should clarify that I'm using VS Code, not WebStorm, to traverse the examples, but even trying to render the app in Chrome I was seeing an error. Changing the file extension to .tsx fixed the issue for me. This was from a standard create-react-app app built using your instructions, with no additional changes to the configuration.

**Comment by abruzzi** [comment]
Thanks for this @softwareliberationarmy. As a general suggestion, all the React components should be extended with `tsx` in our `Bookish` application in the book.
