### ISSUE TITLE
Errata - json-server setup on p.106-107

### ISSUE THREAD

**Issue by softwareliberationarmy** [Apress/Test-Driven-Development-with-React-second-edition-by-Juntao-Qiu#4]
There are a couple of errors with the react-scripts stub-server script that you add:
1. The watch and port options need to have double dashes, not singles (--watch, not -watch)
2. The statement cannot be run from the root directory like you say on p.108. The db.json file relative path should be ./stub-server/db.json 

The full script should be: 
"stub-server": "json-server --watch ./stub-server/db.json --port 8080"

**Comment by abruzzi** [comment]
Yes, I just tried the command (the printed one from PDF), and it was 

```
json-server –watch db.json –port 8080
```

Instead of 

```
json-server --watch db.json --port 8080
```

I suspect that's a word processor auto-correction issue, but thanks for pointing it out.

**Comment by abruzzi** [comment]
For the 2nd point, you can either go to folder `stub-server` first and then launch the `stub-server` or do as you suggested here.
